name: Pull request checks
 
on: [pull_request]
 
permissions:
  pull-requests: read
 
jobs:
  block-autosquash-commits:
    name: Block autosquash commits
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
 
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: paschdan/semantic-pullrequest-action@v1
        with:
          config_file: .commitlint/commitlint.config.ts
          check_title: false
          create_comment: false